name: visualCheXbert
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - intel-openmp=2019.4
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - llvm-openmp=10.0.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - pip=21.0.1
  - python=3.7.7
  - readline=8.1
  - scipy=1.6.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - chardet==4.0.0
    - click==7.1.2
    - filelock==3.0.12
    - idna==2.10
    - joblib==0.14.1
    - numpy==1.20.1
    - packaging==20.9
    - pandas==1.2.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - regex==2020.11.13
    - requests==2.25.1
    - sacremoses==0.0.43
    - scikit-learn==0.22.1
    - sentencepiece==0.1.95
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - tokenizers==0.8.1rc1
    - torch==1.4.0
    - tqdm==4.57.0
    - transformers==3.0.2
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3

